# File: .azure-ci/jobs/test_template.yml

parameters:
  name: ''
  message: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: Job - ${{ parameters.message }}

    pool:
      vmImage: macOS-10.14
    steps:
      - bash: |
          echo ${{ parameters.message }}
        displayName: Step - ${{ parameters.message }}