# File: .azure-ci/stages/stage_scheduled_test.yml

# Stage 2 - Cron job to test formulae

stages:

  - stage: stage_scheduled_test
    displayName: Stage - Scheduled Test on master

    condition: |
      eq(variables['Build.Reason'], 'PullRequest')

    jobs:

      - job: job_scheduled_test
        displayName: Job - Scheduled Test on master

        pool:
          vmImage: macOS-10.14

        steps:

          - bash: |
              FAILING_FORMULAE=()
              for formula in Formulae/*
              do
                echo "Testing $formula"
                brew install $formula
                brew test $formula && brew linkage --test $formula
                if [ $? -eq 1 ]; then
                  FAILING_FORMULAE+=$formula
                fi
              done
              echo "The following formulae failed: $FAILING_FORMULAE"
            displayName: Step - Testing Formulae