# File: .azure-ci/stages/stage_scheduled_test.yml

# Stage 2 - Cron job to test formulae

stages:

  - stage: stage_scheduled_test
    displayName: Scheduled Test on master

    condition: eq(variables['Build.Reason'], 'Schedule')

    jobs:
      - template: /.azure-ci/jobs/test_template.yml
        parameters:
          name: test_stage_cron_job_on_master
          message: Scheduled Test on master