# File: .azure-ci/stages/stage_build_bottles.yml

# Stage 3 - Building bottles on PR

stages:

  - stage: stage_build_bottles
    displayName: Build bottles

    condition: |
      eq(variables['Build.Reason'], 'PullRequest')

    jobs:
      - template: ../jobs/test_template.yml
        parameters:
          name: test_stage_build_bottle
          message: Build bottles
      # - template: .azure-ci/brew_test_bot.yml
      #   parameters:
      #     name: brew_test_bot_macOS_10_14
      #     displayName: for macOS Mojave (10.14)
      #     vmImage: macOS-10.14
      #     xcode: Xcode_10.2

      # - template: .azure-ci/brew_test_bot.yml
      #   parameters:
      #     name: brew_test_bot_macOS_10_13
      #     displayName: for macOS High Sierra (10.13)
      #     vmImage: macOS-10.13
      #     xcode: Xcode_10.1