# File: .azure-ci/stages/stage_scheduled_test.yml

# Stage 2 - Cron job to test formulae

stages:

  - stage: stage_scheduled_test
    displayName: Stage - Scheduled Test on master

    condition: |
      eq(variables['Build.Reason'], 'Schedule')

    jobs:

      - job: job_scheduled_test
        displayName: Job - Scheduled Test on master

        pool:
          vmImage: macOS-10.14

        steps:

          - bash: |
              FAILING_FORMULAE=()
              for formula in Formulae/*
              do
                echo "Testing $formula"
                brew install $formula
                brew test $formula && brew linkage --test $formula
                if [ $? -eq 1 ]; then
                  FAILING_FORMULAE+=$formula
                fi
                FAILING_FORMULAE+=$formula
              done
              if [ ${#FAILING_FORMULAE[@]} -eq 0 ]; then
                echo "All formulae passed the test, there's nothing to worry about."
                echo "We'll try better next time..."
                exit 0
              else
                echo "The following formulae failed: $FAILING_FORMULAE"
                echo "A new PR will be created to bump the revision and rebuild"
                echo "the formulae."
                echo "##vso[task.setvariable variable=failing_formulae;isOutput=true]$FAILING_FORMULAE"
                exit 1
              fi
            displayName: Step - Test Formulae
            name: test_formulae

      - job: job_create_revision_bump_pr
        displayName: Job - Create revision bump PR

        pool:
          vmImage: macOS-10.14

        dependsOn: job_scheduled_test

        condition: failed()

        variables:
          failing_formulae: $[ dependencies.job_scheduled_test.outputs['test_formulae.failing_formulae'] ]

        steps:

          - bash: |
              brew install hub
              git config --global user.name "Ladislas de Toldi"
              git config --global user.email "ladislas@detoldi.me"
              git config --global hub.protocol https
              git config credential.helper '!f() { sleep 1; echo "username=${GITHUB_USER}"; echo "password=${GITHUB_TOKEN}"; }; f'
              hub fetch origin
              hub checkout master
              git reset --hard origin/master
              DATE_TIME=$( date +"%Y/%m/%d@%T" )
              FAILING_FORMULAE_LIST=$( IFS=$'_'; echo "${FAILING_FORMULAE[*]}" )
              git checkout -b revision-bump/$DATE_TIME-$FAILING_FORMULAE_LIST
              DATE_TIME_LITTERAL=$( date +"%Y/%m/%d at %T" )
              for formula in $FAILING_FORMULAE; do
                brew bump-revision $formula --message="- scheduled CI test on $DATE_TIME_LITTERAL"
              done
              hub pull-request --push
            displayName: Step - Create revision bump PR
            env:
              HOMEBREW_NO_AUTO_UPDATE: 1
              HUB_VERBOSE: 1
              FAILING_FORMULAE: $(failing_formulae)
              GITHUB_USER: $(github_user)
              GITHUB_EMAIL: $(github_email)
              GITHUB_TOKEN: $(github.token)