# File: .azure-ci/stages/stage_pull_revision_bump.yml

# Stage 5 - Auto publish revision bumps

stages:

  - stage: stage_pull_revision_bump
    displayName: Stage - Pull revision bump

    dependsOn:
      - stage_upload_bottles

    condition: |
      and(
        succeeded('stage_upload_bottles'),
        eq(variables['Build.Reason'], 'PullRequest'),
        eq(variables['System.PullRequest.IsFork'], False),
        contains(variables['System.PullRequest.SourceBranch'], 'revision-bump')
      )

    jobs:
      - template: /.azure-ci/jobs/test_template.yml
        parameters:
          name: test_stage_publish_revision_bump
          message: Publish revision bump

      - job: test_pr_message_condition
        displayName: Test PR message condition

        pool:
          vmImage: macOS-10.14

        steps:

        - bash: |
            echo "The PR can be merged as the name is ok"
            git log
            git show
            echo $RANDOM
          displayName: Step - Test PR message condition